"""Userga lan va lng qo'shildi. Category image qo'shildi

Revision ID: 193a13d773cb
Revises: 7a62b6b3a637
Create Date: 2024-07-24 00:17:38.809693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193a13d773cb'
down_revision = '7a62b6b3a637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('image_url', sa.String(), nullable=False))
    op.add_column('users', sa.Column('image', sa.String(), nullable=True))
    op.add_column('users', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lng')
    op.drop_column('users', 'lat')
    op.drop_column('users', 'image')
    op.drop_column('category', 'image_url')
    # ### end Alembic commands ###
