"""Userga lan va lng qo'shildi image ham.

Revision ID: 6488cffbeca4
Revises: 193a13d773cb
Create Date: 2024-07-24 00:28:27.022714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6488cffbeca4'
down_revision = '193a13d773cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
