"""add new field users -  address 

Revision ID: 709e290003dc
Revises: 81812556a62c
Create Date: 2024-07-16 07:11:18.658158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709e290003dc'
down_revision = '81812556a62c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
