"""bir necha o'zgarishlar

Revision ID: 7a62b6b3a637
Revises: 9a22ec481ccc
Create Date: 2024-07-23 04:00:26.986353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a62b6b3a637'
down_revision = '9a22ec481ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
