"""Add location column to order table

Revision ID: c7924af6bd7c
Revises: 6488cffbeca4
Create Date: 2024-07-26 17:22:35.500806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7924af6bd7c'
down_revision = '6488cffbeca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('location', sa.String(), nullable=True))
    op.alter_column('order', 'shipping_address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'shipping_address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('order', 'location')
    # ### end Alembic commands ###
