"""Modellarni async uchun moslab chiqildi

Revision ID: e28faf20bb23
Revises: e324385b36e7
Create Date: 2024-07-20 18:14:30.448986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e28faf20bb23'
down_revision = 'e324385b36e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cart', 'created_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('cart_items', 'cart_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cart_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cart_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cart_items', 'created_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint(None, 'category', ['name'])
    op.alter_column('images', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('images', 'url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint('images_product_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'products', ['product_id'], ['id'])
    op.alter_column('order', 'order_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('order', 'order_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order', 'order_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('order', 'shipping_address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('order', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_details', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_details', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_details', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_details', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('products', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('products_category_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'category', ['category_id'], ['id'])
    op.add_column('users', sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint('users_telegram_id_key', 'users', type_='unique')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_telegram_id_key', 'users', ['telegram_id'])
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'create_date')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_category_id_fkey', 'products', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('order_details', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('order_details', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_details', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_details', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order', 'shipping_address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('order', 'order_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('order', 'order_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order', 'order_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key('images_product_id_fkey', 'images', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('images', 'url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('images', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'category', type_='unique')
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('cart_items', 'created_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('cart_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cart_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cart_items', 'cart_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cart', 'created_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('cart', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
